import scrapy

# these are the indexes for data scraped by the full (14-day) spider
# these indexes are converted to dates by post_scrape.py
class FullScrapeItem(scrapy.Item):
    name = scrapy.Field()
    p_0 = scrapy.Field()
    p_1 = scrapy.Field()
    p_2 = scrapy.Field()
    p_3 = scrapy.Field()
    p_4 = scrapy.Field()
    p_5 = scrapy.Field()
    p_6 = scrapy.Field()
    p_7 = scrapy.Field()
    p_8 = scrapy.Field()
    p_9 = scrapy.Field()
    p_10 = scrapy.Field()
    p_11 = scrapy.Field()
    p_12 = scrapy.Field()
    p_13 = scrapy.Field()
    p_14 = scrapy.Field()
    dv_0 = scrapy.Field()
    dv_1 = scrapy.Field()
    dv_2 = scrapy.Field()
    dv_3 = scrapy.Field()
    dv_4 = scrapy.Field()
    dv_5 = scrapy.Field()
    dv_6 = scrapy.Field()
    dv_7 = scrapy.Field()
    dv_8 = scrapy.Field()
    dv_9 = scrapy.Field()
    dv_10 = scrapy.Field()
    dv_11 = scrapy.Field()
    dv_12 = scrapy.Field()
    dv_13 = scrapy.Field()
    dv_14 = scrapy.Field()
    pass
