name: Docker Image CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - name: Log in to Docker Hub
      uses: docker/login-action@${SHORT_SHA}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build extract image
      run: docker build . --file ./build/backend/extract/Dockerfile --tag extract_test
    - name: Push extract image
      run: docker push ${{secrets.DOCKER_USER}}/osrs_item_investment_project
    - name: Build transform image
      run: docker build . --file ./build/backend/transform/Dockerfile --tag transform_test
    - name: Push transform image
      run: docker push ${{secrets.DOCKER_USER}}/osrs_item_investment_project
    - name: Build app image
      run: docker build . --file ./build/frontend/app/Dockerfile --tag app_test
    - name: Push app image
      run: docker push ${{secrets.DOCKER_USER}}/osrs_item_investment_project
