name: Docker Image CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSSWORD
    - name: Build extract image
      run: docker build . --file build/backend/extract/Dockerfile --tag extract_test:$(date +%s)
    - name: Push extract image
      run: docker push ${{secrets.DOCKER_USER}}/osrs_item_investment_project
    - name: Build transform image
      run: docker build . --file build/backend/transform/Dockerfile --tag transform_test:$(date +%s)
    - name: Push transform image
      run: docker push ${{secrets.DOCKER_USER}}/osrs_item_investment_project
    - name: Build app image
      run: docker build . --file build/frontend/app/Dockerfile --tag app_test:$(date +%s)
    - name: Push app image
      run: docker push ${{secrets.DOCKER_USER}}/osrs_item_investment_project
