name: Docker Image CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker logout
      run: docker logout
    - name: docker login
      run:
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Clean up unused images
      run: docker image prune -f
    - name: Build app image
      run: docker build . --file build/frontend/app/Dockerfile --tag app_test
    - name: Tag app image
      run: docker tag app_test ${{secrets.DOCKER_USER}}/osrs_item_investment_project:app_test
    - name: Push app image
      run: docker push ${{secrets.DOCKER_USER}}/osrs_item_investment_project:app_test